Version 0.0.2
horoyami/TableConstructor pull request #1
Opened 2018-10-20 21:44 UTC by horoyami

Переделал полностью архитектуру. Попытался сделать ее достаточно модульной.
На кнопку добавить теперь можно нажимать много раз, тем самым добавляя нужное колличество строк и столбцов.
На редактируемом поле доступна комбинация клавиш Cntrl+Enter, которая вставляет строку после текущей и переходит на ее первый элемент.
Произведены некоторые улучшения в определении координат элементов. Границы теперь не прыгают. 
Добавлена небольшая поддержка настроек таблицы при конструкции.

Про JSDoc знаю, добавлю в следующий раз

2018-10-21 08:22 UTC, gohabereg requested changes
Весь код нужно документировать по jsdoc

2018-10-21 08:22 UTC, gohabereg commented on src/Border.css
> +.b-bor {
Названия файлов всё-таки принято писать с маленькой буквы. И лучше не лениться писать понятные названия классов. Через год уже не вспомнишь, что значит `b-bor`

2018-10-21 08:22 UTC, gohabereg commented on src/Border.js
> +export let Border = function (table, classes) {
Если переменная не переназначения, нужно использовать const

2018-10-21 08:22 UTC, gohabereg commented on src/Border.js
> +    let self = this;
Тоже const

2018-10-21 08:22 UTC, gohabereg commented on src/Border.js
> +        self._addButton = document.createElement("img");
Для создания элементов и назначения всех классов и атрибутов лучше сделать отдельный метод

2018-10-21 08:22 UTC, gohabereg commented on src/Border.js
> +    function _generateElement() {
Не понятно, что за Element

2018-10-21 08:22 UTC, gohabereg commented on src/TableConstructor.js
> +        let paddingCorrectHigh = (isWrapper) ? ((-2) * 10 - 1) : (-10);
Магические числа нужно выносить в константы с понятными именамм

2018-10-21 08:22 UTC, gohabereg commented on src/TableConstructor.js
> +        if (hover_block === table_editor) {
Имена переменных лучше в camelCase

2018-10-21 08:22 UTC, gohabereg commented on src/TableConstructor.js
> +            if (event.target.className === "tg-inputField" && !cntrlPass) {
`classList.includes`

2018-10-21 08:22 UTC, gohabereg commented on src/TableConstructor.js
> +        if (event.code === "Enter") {
Крупные обработчики лучше выносить в отдельные методы

2018-10-21 10:18 UTC, horoyami commented on src/Border.css
> +.b-bor {
Насчет `b-*`. Я использовал эти префексы, чтобы не было конфликтов имен с возможными другими стилями. Есть ли более распространенная практика как это делать?

2018-10-21 10:20 UTC, gohabereg commented on src/Border.css
> +.b-bor {
Мы в проектах стараемся придерживаться методологии БЭМ
https://ru.bem.info

2018-10-22 07:19 UTC, horoyami commented on src/Border.css
> +.b-bor {
Понимаю. Но меня смущает, что довольно слабая гарантия, что имена не будут пересекаться между модулями в том же БЭМ. Например если в 2х модулях есть похожий блок высшего уровня, авторы которых захотели назвать его одинаково.

2018-10-22 07:19 UTC, horoyami commented on src/Border.css
> +.b-bor {
Понимаю. Но меня смущает, что довольно слабая гарантия, что имена не будут пересекаться между модулями в том же БЭМ. Например если в 2х модулях есть похожий блок высшего уровня, авторы которых захотели назвать его одинаково.

2018-10-22 07:21 UTC, horoyami commented on src/Border.css
> +.b-bor {
Понимаю. Но меня смущает, что довольно слабая гарантия, что имена не будут пересекаться между модулями в том же БЭМ. Например если в 2х модулях есть похожий блок высшего уровня, авторы которых захотели назвать его одинаково.

2018-10-22 07:59 UTC, gohabereg commented on src/Border.css
> +.b-bor {
Ты можешь использовать какой-нибудь префикс для всех классов. Что-нибудь уникальное, но при этом всё-таки значащее. У нас например в некоторых модулях используется префикс cdx или что-то связанное с названием модуля

2018-10-22 07:59 UTC, gohabereg commented on src/Border.css
> +.b-bor {
Ты можешь использовать какой-нибудь префикс для всех классов. Что-нибудь уникальное, но при этом всё-таки значащее. У нас например в некоторых модулях используется префикс cdx или что-то связанное с названием модуля

2018-10-22 08:05 UTC, gohabereg commented on src/Border.css
> +.b-bor {
Ты можешь использовать префикс ко всем классам. Что-нибудь уникальное, но при этом значащее. У нас в модулях используется или cdx-, или что-то связанное с названием модуля

2018-10-22 08:28 UTC, gohabereg commented on src/Border.css
> +.b-bor {
Ты можешь использовать какой-нибудь префикс для всех классов. Что-то уникальное, но при этом значащее. У нас в модулях мы часто используем `cdx-` или что-нибудь связанное с названием

2018-10-22 08:30 UTC, gohabereg commented on src/Border.css
> +.b-bor {
Ты можешь использовать какой-нибудь префикс для всех классов. Что-то уникальное, но при этом значащее. У нас в модулях мы часто используем `cdx-` или что-нибудь связанное с названием

2018-10-22 08:30 UTC, gohabereg commented on src/Border.css
> +.b-bor {
Ты можешь использовать какой-нибудь префикс для всех классов. Что-то уникальное, но при этом значащее. У нас в модулях мы часто используем `cdx-` или что-нибудь связанное с названием

2018-10-22 08:34 UTC, horoyami commented on src/Border.css
> +.b-bor {
Test

2018-10-22 08:35 UTC, gohabereg commented
Кстати, может будет интересно про версии почитать — https://semver.org/.
Так как ты переписал всю архитектуру, то скорее всего поменялся интерфейс модуля. Если добавились новые фичи, то версия должна быть 0.1.0. Если все совсем поменялось и обратной совместимости нет, то 1.0.0.

0.0.2 будет только если были какие-то небольшие фиксы

2018-10-22 08:43 UTC, gohabereg commented on src/Border.css
> +.b-bor {
Ты можешь использовать какой-нибудь префикс для всех классов. Что-то уникальное, но при этом значащее. У нас в модулях мы часто используем `cdx-` или что-нибудь связанное с названием

2018-10-22 18:53 UTC, horoyami commented
Я поправил все, на что вы обратили внимание и пару своих вещей

2018-10-22 19:02 UTC, horoyami commented
Я поправил все, на что вы обратили внимание и пару своих вещей

2018-10-22 19:03 UTC, horoyami commented
@gohabereg Я поправил все, на что вы обратили внимание и пару своих вещей

2018-10-22 21:12 UTC, gohabereg requested changes
Реквест большой, поэтому смотреть становится трудно. Лучше сфокусируйся пока на правках, а новую функциональность уже в следующих реквестах добавлять

И добавь в реквест webpack.config.js файл

2018-10-22 21:12 UTC, gohabereg commented on src/borderMenu.css
> +.TCM__border-menu__add-button {
Не совсем по БЭМ получается. Лучше общий префикс делать через дефис: `TCM-border-menu`

2018-10-22 21:12 UTC, gohabereg commented on example.js
> +let table = document.getElementsByClassName("main_wrapper")[0];
Лучше тогда `querySelector`

2018-10-22 21:12 UTC, gohabereg commented on example.js
> +let table_editor = new TableConstructor({width: "800px"});
Не очень удобно задавать размер строкой. Модуль сам может добавить px в конструкторе.

2018-10-22 21:12 UTC, gohabereg commented on index.html
> +    <link rel="stylesheet" href="src/tableConstructor.css">
Если используешь webpack, посмотри в сторону style-loader, чтобы css включать в js сборку

2018-10-22 21:12 UTC, gohabereg commented on src/borderMenu.css
> +.TCM__border-menu_hidden {
Тут скорее пожелание. У нас принято модификатор обозначать через `--`. Просто `_` после `__` не очень хорошо читается

2018-10-22 21:12 UTC, gohabereg commented on src/borderMenu.js
> +        self._addButton = document.createElement("img");
Упоминал уже о том, что лучше выносить создание элементов в отдельный метод. Например в данном случае код из 4 строчек сократится в 1

2018-10-22 21:12 UTC, gohabereg commented on src/borderMenu.js
> +        self._addButton.setAttribute("src", "./src/img/plus.svg");
svg кстати тоже можно загружать через webpack прямо в сборку. Но это не обязательно в этом реквесте, чтобы не разрастался

2018-10-22 21:12 UTC, gohabereg commented on src/borderMenu.js
> +        self._elem.classList.add(classes[0], "TCM__border-menu_hidden");
Стоит передать классы объектом. Сразу будет понятно, что тут за значение

2018-10-22 21:12 UTC, gohabereg commented on src/tableConstructor.js
> +export let TableConstructor = function (extra) {
Тут const

2018-10-22 21:12 UTC, gohabereg commented on src/tableConstructor.js
> +    const PADDING_CORRECT_END_FROM_WRAPPER = ((-2) * 10 - 1);
А что значит CORRECT?

2018-10-22 21:12 UTC, gohabereg commented on src/tableConstructor.js
> +            _activeHorBorder(elem.top - tableEditorPos.y1 + paddingCorrectStart);
`active` не является глаголом, лучше тогда `activate`

2018-10-22 21:12 UTC, gohabereg commented on src/tableConstructor.js
> +        if (elem.y - elem.top <= PADDING && elem.y - elem.top >= 0) {
Такие условия можно вынести в переменные с каким-нибудь понятным названием, например `clickOnTopBorder`

2018-10-22 21:12 UTC, gohabereg commented on src/tableConstructor.js
> +    function _dellayAddButton(pos) {
Непонятное название

2018-10-22 21:12 UTC, gohabereg commented on src/tableConstructor.js
> +        if (table.children.length === 1)
К каждому кейсу стоит добавить небольшой коммент. Зачем проверка, почему именно такая и т.д.

2018-10-22 21:12 UTC, gohabereg commented on src/tableConstructor.js
> +                if (div.innerText !== "")
Тут стоит сделать div.innerText.trim(), т.к. там могут быть пробелы

2018-10-22 21:12 UTC, gohabereg commented on src/tableConstructor.js
> +    function _pressedEnter(event) {
`_enterPressed`

2018-10-22 21:12 UTC, gohabereg commented on src/tableConstructor.js
> +    tableEditor.addEventListener("addButtonClick", (event) => {
`addButtonClick` немного смущает, т.к. `add` воспринимается как глагол. Стоит подумать над другим названием, например `plusButton`

2018-10-22 21:12 UTC, gohabereg commented on src/tableConstructor.js
> +    document.addEventListener("keyup", () => {
Не стоит вешать события на глобальные объекты. Если тебе нужно проверить, зажат ли контрол, то в объекте KeyboardEvent для этого есть специальное поле

2018-10-22 21:12 UTC, gohabereg commented on src/tableConstructor.js
> +    document.addEventListener("keydown", (event) => {
Не стоит вешать на документ, лучше повесить на обертку модуля

2018-10-22 21:12 UTC, gohabereg commented on src/tableGenerator.js
> + * @param table - tbody element of table to be generated
Всем параметрам надо указать тип `@param {HTMLElement} table - ...`

2018-10-22 21:12 UTC, gohabereg commented on src/tableGenerator.js
> +    let numberColumns = 0;
number**Of**Columns

2018-10-22 21:12 UTC, gohabereg commented on src/tableGenerator.js
> +    let numberStrings = 0;
Лучше все таки использовать rows, а не strings

2018-10-22 21:12 UTC, gohabereg commented on src/tableGenerator.js
> + * @param table - tbody element of table to be generated
Не пробовал кстати посмотреть в сторону HTMLTableSectionElement. Там вроде есть какие-то встроенные методы для работы с рядами

2018-10-22 21:12 UTC, gohabereg commented on src/tableGenerator.js
> +    this.addColumnTable = function (pos = Infinity) {
Думаю, можно просто addColumn

2018-10-22 21:12 UTC, gohabereg commented on src/tableGenerator.js
> +    this.addStringTable = function (pos = Infinity) {
И тут просто addRow

2018-10-22 21:13 UTC, gohabereg commented
> @gohabereg Я поправил все, на что вы обратили внимание и пару своих вещей

И лучше на ты)

2018-10-22 21:21 UTC, horoyami commented on index.html
> +    <link rel="stylesheet" href="src/tableConstructor.css">
На счет конф. файла) Его нет в репе потому что его нет вообще пока)
А на счет style-loadera. У меня возникает такой вопрос. Получается css будет полностью вшит в js и польщователю нашего модуля даже не обязательно пользоваться webpack?

2018-10-22 21:25 UTC, horoyami commented on src/borderMenu.js
> +        self._addButton = document.createElement("img");
Что-то Я не совсем понимаю. В этом файле каждый элемент генерируется своим методом с соответствующим названием, а потом происходит общее создание всего в методе init. Что же тогда вы имеете в виду под "отдельный метод"

2018-10-22 23:02 UTC, gohabereg commented on index.html
> +    <link rel="stylesheet" href="src/tableConstructor.css">
Пользователь в идеале должен просто скачать одни js файл. Вебпак используется только при разработке

2018-10-22 23:03 UTC, gohabereg commented on src/borderMenu.js
> +        self._addButton = document.createElement("img");
Отдельный метод, в который передаешь название тега, классы и все атрибуты, а он возвращает созданный элемент

2018-10-22 23:09 UTC, gohabereg commented on src/borderMenu.js
> +        self._addButton = document.createElement("img");
У тебя сейчас в нескольких местах одинаковый код: создаётся элемент, назначаются классы и атрибуты. Вынеси это в одну функцию

2018-10-23 17:23 UTC, horoyami commented on example.js
> +let table_editor = new TableConstructor({width: "800px"});
Понимаю в чем негодование. Но я хотел сделать настройки похожими на css. К тому же, зададание условных едениц можно менять. То есть использовать % вместо пикселей, для примера. Думаете, будет лучше сделать особенную настройку для кажой из условных едениц, но числовую?

2018-10-23 20:53 UTC, horoyami commented
Все посмотрел, все исправил, кроме некоторых вещей.

Все что касается webpack, package.json и связанными с ними вещами: Я хочу в следующем реквесте еще немного поработать над модульностью и действительно сделать структуру проекта таким образом, чтобы она генерировала лишь 1 JS файл, к которому можно подключиться. Так же я назову эту версию 1.0.0. Все эти изменения войдут уже туда.

Что касается объекта настроек, что передается в главный кнструктор перед созданием: думаю, нужно будет получше подумать над его API. Я его сейчас не изменил. К его дороботке основательной проработке я планирую перейти в одном из следующих реквестов.

Так же я убрал событие с document и навесил его на сонтейнер всего модуля. Но теперь я не совсем понимаю, как пользователь вообще должен их вызывать. Собственно, я думаю, Механизм горячих клавиш тоже нужно отдельно основательно проработать.

И самое главное. Я в принципе перестал немного понимать, что в итоге мы хотим от модуля. Изначально я представлял его как некий мини клон excel, но видимо это совсем не так.

2018-10-25 16:43 UTC, neSpecc requested changes

2018-10-25 16:43 UTC, neSpecc commented on src/tableGenerator.js
> +        const cell = DOM.createDOMElement("td", ["TCM-editable-table__cell"]);
вынести классы в словарь

2018-10-25 16:43 UTC, neSpecc commented on src/tableGenerator.js
> +        elem.insertBefore(str, (pos >= elem.children.length) ? null : elem.children[pos]);
вынести условие в переменную

2018-10-25 16:43 UTC, neSpecc commented on src/tableConstructor.js
> +export const TableConstructor = function (extra) {
переписать на класс

2018-10-25 16:43 UTC, neSpecc commented on src/tableConstructor.js
> +        if (extra === undefined)
подключить линтер

2018-10-25 16:43 UTC, neSpecc commented on src/tableConstructor.js
> +    function _createTableFrame() {
_createMainContainer

2018-10-25 16:43 UTC, neSpecc commented on src/tableConstructor.js
> +        _createTable();
create должны вернуть элемент, который ты запишешь в this

```js
// в конструкторе
this.container = this.createContainer()
```

2018-10-25 16:43 UTC, neSpecc commented on src/borderMenu.js
> +export const BorderMenu = function (table, classes) {
PlusButton

2018-10-25 16:43 UTC, neSpecc commented on src/borderMenu.js
> +export const BorderMenu = function (table, classes) {
тоже на класс переписать

2018-10-25 16:43 UTC, neSpecc commented on src/borderMenu.js
> +    function _generate1pxLine() {
не привязывать названия переменных к стилям

2018-10-25 16:43 UTC, neSpecc commented on src/horizontalBorderMenu.css
> +.TCM-border-menu--horizontal {
не использовать капслок

2018-10-25 16:43 UTC, neSpecc commented on src/positionUtils.js
> +    function getPositionOfElement(elem) {
getCoords

2018-10-25 16:43 UTC, neSpecc commented on src/tableConstructor.js
> +        while (pos < parent.children.length && parent.children[pos++] !== child) ;
неявный while

2018-10-25 16:43 UTC, neSpecc commented on src/tableConstructor.js
> +        while (!(hoverBlock === null || hoverBlock.tagName === "TD" || hoverBlock === tableEditor))
{}

2018-10-25 16:43 UTC, neSpecc commented on src/tableGenerator.js
> +export const TableGenerator = function (table = null) {
избавиться от лишних сущностей

2018-10-28 11:48 UTC, merged