Version 1.0.0
horoyami/TableConstructor pull request #2
Opened 2018-10-28 11:51 UTC by horoyami

Переделал концепцию активации тул баров. Теперь событий в разы меньше. Так же переписал все на классы. Упростил почти все сущности. От некоторых избавился. Подключил линтер.

2018-10-28 12:46 UTC, gohabereg requested changes

2018-10-28 12:46 UTC, gohabereg commented on src/activatingAreaAroundContainer.js
> +export class ActivatingAreaAroundContainer {
очень сложное и не понятное название

2018-10-28 12:46 UTC, gohabereg commented on src/activatingAreaAroundContainer.js
> +   * @param {boolean} isOutside - If true, then check the output from the container
Тоже не понял, зачем этот параметр. Что значит `check the output from the container`?

2018-10-28 12:46 UTC, gohabereg commented on src/borderToolBar.js
> +    button.classList.add(CSS.plusButton);
createDOMElement принимает и классы и атрибуты.  Туда их и передай

2018-10-28 12:46 UTC, gohabereg commented on src/borderToolBar.js
> +    button.firstChild.addEventListener('click', (event) => {
Почему не повесить на весь контейнер?

2018-10-28 12:46 UTC, gohabereg commented on src/borderToolBar.js
> +  _generateHighlightingLineCoveringBorder(style) {
Очень сложное название. К тому же не очень правильное с точки зрения английского.

2018-10-28 12:46 UTC, gohabereg commented on src/borderToolBar.js
> +  _generateHighlightingLineCoveringBorder(style) {
Аргумент не используется, можно убрать

2018-10-28 12:46 UTC, gohabereg commented on src/documentUtils.js
> +function _checkIsNotMissing(elem) {
Сложное название.

2018-10-28 12:46 UTC, gohabereg commented on src/documentUtils.js
> + * Checks unless the item is missing
Что это значит?

2018-10-28 12:46 UTC, gohabereg commented on src/documentUtils.js
> + * @returns {boolean} true if element contains something
Не соответствует тому, что происходит на самом деле

2018-10-28 12:46 UTC, gohabereg commented on src/table.js
> +   * @param {number} index
Не соответствует коду

2018-10-28 12:46 UTC, gohabereg commented on src/table.js
> +  get selectedSell() {
Опечатка

2018-10-28 12:46 UTC, gohabereg commented on src/table.js
> +   * returns selected/edited sell
sell -> cell

2018-10-28 12:52 UTC, horoyami commented on src/borderToolBar.js
> +    button.firstChild.addEventListener('click', (event) => {
Потому что контейнер, где лежит кнопка содержит другие элементы, и как следствие, больше в размере, чем кнопка. Придется делать проверку, что нажата именно кнопка

2018-10-28 13:25 UTC, horoyami commented
@gohabereg Пофиксил, вроде. Оказывается это сложно - давать названия абстрактным компонентам.

2018-10-29 10:14 UTC, neSpecc requested changes

2018-10-29 10:14 UTC, neSpecc commented on src/containerWithDetectionAreas.js
> +   * @param style - additional styles
не указан тип переменных

2018-10-29 10:14 UTC, neSpecc commented on src/table.css
> +.tcm-editable-table__cell {
давай подключим postcss-loader и плагин postcss-nested
Тогда можно будет написать стили красивее

```pcss
.tcm-editable-table {
   ...
  &__cell {
     ...
     &--focus {
        ...
     }
  }
}
```

2018-10-29 10:14 UTC, neSpecc commented on src/documentUtils.js
> + * @param {array} children - child elements of creating element
{Element[]}

2018-10-29 10:14 UTC, neSpecc commented on src/documentUtils.js
> +export function createDOMElement(tagName, cssClasses = null, attrs = null, children = null) {
давай назовем покороче, например просто `create()` или `el()`

2018-10-29 10:14 UTC, neSpecc commented on src/table.js
> +  table: 'tcm-editable-table',
блок лучше поместить выше, над элементами

2018-10-29 10:14 UTC, neSpecc commented on src/tableConstructor.js
> +   * @param coord - where show
не указан тип и возможные значения

2018-10-29 10:14 UTC, neSpecc commented on src/tableConstructor.js
> +    this._container.htmlElement.addEventListener('click', (event) => {
надо бы вынести обработчики в отдельные методы

2018-10-29 10:14 UTC, neSpecc commented on src/tableConstructor.js
> +   * @param coord - coords of mouse
не указан тип

2018-10-29 10:14 UTC, neSpecc commented on src/tableConstructor.js
> +    this._container.htmlElement.appendChild(this._verticalToolBar.htmlElement);
надо отделить смысловые части пустыми строками и написать комментарии к ним

2018-10-29 10:14 UTC, neSpecc commented on src/tableConstructor.js
> +    this._table = this._createBlankTable();
не все свойства объявлены (например, нет this.timer = null)

2018-10-29 10:14 UTC, neSpecc commented on src/tableConstructor.js
> +    this._timer = setTimeout(() => {
лучше все же подробнее написать, что за таймер

2018-10-29 18:20 UTC, horoyami commented
@neSpecc Посмотрел и поправил подобные ошибки. Так же постарался описать таймер, надеюсь, понятно вышло. Добавил SCSS. postcss почему-то никак не хочет понимать sass синтаксист(&) позже попробую разобраться

2018-10-29 19:20 UTC, neSpecc approved these changes

2018-10-30 08:06 UTC, merged