Is it plugin?
horoyami/TableConstructor pull request #7
Opened 2018-11-01 13:04 UTC by horoyami

2018-11-01 14:16 UTC, gohabereg requested changes

2018-11-01 14:16 UTC, gohabereg commented on src/plugin.js
> +export class CodexTable {
Лучше просто Table

2018-11-01 14:16 UTC, gohabereg commented on src/plugin.js
> +    return false;
Этот плагин будет в тулбоксе

2018-11-01 14:16 UTC, gohabereg commented on src/plugin.js
> +    return this._element.htmlElement;
Нужно сделать так, чтобы можно было передать данные при рендере.

2018-11-01 14:16 UTC, gohabereg commented on src/plugin.js
> +    let data = [];
const

2018-11-01 15:09 UTC, neSpecc requested changes

2018-11-01 15:09 UTC, neSpecc commented on example/example.js
> +  height: 3,
давай назовем rows и cols

2018-11-01 15:09 UTC, neSpecc commented on src/plugin.js
> +   *   data — previously saved data
параметры не так документируются

2018-11-01 15:09 UTC, neSpecc commented on src/plugin.js
> +    return this._element.htmlElement;
они передаются в конструкторе

2018-11-01 15:09 UTC, neSpecc commented on src/plugin.js
> +    const height = table.children.length;
надежнее сделать this._element.querySeletorAll('tr') и переберать найденные элементы

2018-11-01 15:09 UTC, neSpecc commented on src/borderToolBar.js
> +    const line = create('div', [CSS.highlightingLine, this._additionalStyles.highlightingLine]);
не явное предназначение `this._additionalStyles.highlightingLine`

2018-11-01 15:09 UTC, neSpecc commented on src/plugin.js
> +      data.push([]);
поместить после цикла по td

2018-11-01 15:09 UTC, neSpecc commented on src/plugin.js
> +        data[i].push(cell.firstChild.innerHTML);
cell.firstChild - не надежное обращение

2018-11-01 15:09 UTC, neSpecc commented on src/plugin.js
> +    const table = this._element.tbody;
искать от toolsContent

2018-11-01 15:09 UTC, neSpecc commented on src/plugin.js
> +    return {
return data

2018-11-01 15:09 UTC, neSpecc commented on example/example.js
> +  height: 3,
и передать их в config

2018-11-01 15:09 UTC, neSpecc commented on src/table.js
> +    return this._table.parentElement.parentElement;
не надежное обращение

2018-11-01 15:09 UTC, neSpecc commented on src/table.js
> +      if (event.code === 'Enter' && !event.shiftKey) {
лучше проверять keyCode

2018-11-01 15:09 UTC, neSpecc commented on src/tableConstructor.js
> +    for (let i = 0; i < data.width; i++) {
учесть, что данных может быть больше, чем width (cols) и height (rows)

2018-11-01 15:09 UTC, neSpecc commented on src/tableConstructor.js
> +        const content = row.children[j].firstElementChild;
не привязываться к разметке

2018-11-01 15:09 UTC, neSpecc commented on src/tableConstructor.js
> +   * Processes additional information transmitted with the event and applies the necessary actions
написать, что конкретно он делает

2018-11-01 15:09 UTC, neSpecc commented on src/tableConstructor.js
> +   * @param {object} event
не описан тип и назначение параметра

2018-11-01 15:09 UTC, neSpecc commented on src/tableConstructor.js
> +    if ((typeof event.detail) !== "number" && event.detail !== null) {
разбить на части, описать в комментах

2018-11-01 15:09 UTC, neSpecc commented on src/tableConstructor.js
> +  get tbody() {
не использовать привязку к разметке

2018-11-01 15:09 UTC, neSpecc commented on src/tableConstructor.js
> +    const index = this._calculateToolBarPosition(this.tbody, this._coveredBlock.parentElement);
this._coveredBlock.parentElement — не надежно

2018-11-01 15:09 UTC, neSpecc commented on src/tableConstructor.js
> +      const index = this._calculateToolBarPosition(this.tbody, this._table.selectedCell.parentElement, false);
постараться не полагаться на parentElement

2018-11-01 15:09 UTC, neSpecc commented on webpack.config.js
> +        use: ["style-loader", "css-loader", "postcss-loader", "sass-loader"]
оставить только postcss

2018-11-06 15:15 UTC, neSpecc requested changes

2018-11-06 15:15 UTC, neSpecc commented on src/borderToolBar.js
> +    button.querySelector('svg').addEventListener('click', (event) => {
почему не повесить на button?

2018-11-06 15:15 UTC, neSpecc commented on src/borderToolBar.js
> +      this._toolBar.dispatchEvent(e);
toolbar маленькими буквами

2018-11-06 15:15 UTC, neSpecc commented on src/img/plus.svg
> +        <path d="M6.44 4.64h3.7a.9.9 0 1 1 0 1.8h-3.7v3.7a.9.9 0 1 1-1.8 0v-3.7H.9a.9.9 0 0 1 0-1.8h3.74V.9a.9.9 0 0 1 1.8 0v3.74z" id="a"/>
надо оптимизировать svg

2018-11-06 15:15 UTC, neSpecc commented on src/plugin.js
> +    this._element = new TableConstructor(data, config);
это не элемент, надо выбрать название более правильное

2018-11-06 15:15 UTC, neSpecc commented on src/table.js
> +   * @param {number} index, if insert in end
at the end

2018-11-06 15:15 UTC, neSpecc commented on src/table.js
> +   * @param {number} index, if insert in end
комментарий не по формату jsdoc

2018-11-06 15:15 UTC, neSpecc commented on src/table.js
> +   * @param {number} index, if insert in end
что означает index не объяснено

2018-11-06 15:15 UTC, neSpecc commented on src/table.js
> +   * @param {number} index, -1 if insert in end
не по jsdoc

2018-11-06 15:15 UTC, neSpecc commented on src/tableConstructor.js
> +    if (data.content !== undefined) {
что такое content?

2018-11-06 15:15 UTC, neSpecc commented on src/tableConstructor.js
> +   * @param {object} size - contains number of rows and cols
описать структуру объекта

2018-11-06 15:15 UTC, neSpecc commented on src/tableConstructor.js
> +   * @return {object} - cols and rows
описать структуру объекта : `{{cols: number, rows: number}}`

2018-11-06 15:15 UTC, neSpecc commented on src/tableConstructor.js
> +    const contentRows = (isValidArray) ? data.content.length : undefined;
скобки не нужны

2018-11-06 15:15 UTC, neSpecc commented on src/tableConstructor.js
> +   * @param {TableData} data - data for insert in table
for inserting или to insert

2018-11-06 15:15 UTC, neSpecc commented on src/tableConstructor.js
> +   * @param {TableData} data - data for insert in table
to the table

2018-11-06 15:15 UTC, neSpecc commented on src/tableConstructor.js
> +  _findParentByTag(element, tag) {
погугли closest

2018-11-06 15:15 UTC, neSpecc commented on src/tableConstructor.js
>    _clickListener(event) {
cellClicked (если это клик на ячейку). Сейчас не понятно, какой клик

2018-11-06 15:15 UTC, neSpecc commented on src/tableConstructor.js
> +      const detailHasData = (typeof event.detail) !== 'number' && event.detail !== null;
скобки не нужны

2018-11-06 15:15 UTC, neSpecc commented on src/tableConstructor.js
> +   * @param {KeyboardEvent} event
надо в описании еще указать, на каком элементе детектится нажатие клавиш

2018-11-06 15:15 UTC, neSpecc commented on src/tableConstructor.js
> +      const index = this._calculateToolBarPosition(this._findParentByTag(this._table.selectedCell, "TR"), false);
вынести поиск элемента в переменную

2018-11-08 16:36 UTC, neSpecc requested changes

2018-11-08 16:36 UTC, neSpecc commented on .gitignore
> +tableConstructor.js
старье

2018-11-08 16:36 UTC, neSpecc commented on src/table.scss
> +/* tc- project's prefix*/
.pcss

2018-11-08 16:36 UTC, neSpecc commented on src/table.scss
> +/* tc- project's prefix*/
.pcss

2018-11-08 16:36 UTC, neSpecc commented on src/table.js
>  import './table.scss';
.pcss

2018-11-08 16:36 UTC, neSpecc commented on src/tableConstructor.js
> +    const isValidArray = data.content instanceof Array;
Array.isArray();

2018-11-08 16:36 UTC, neSpecc commented on src/tableConstructor.js
> +    const configRows = (typeof (+config.rows) === 'number' && config.rows > 0) ? config.rows : undefined;
```js
isNaN(parseInt("1")) ? parseInt("1") : undefined;
```

2018-11-08 16:36 UTC, neSpecc commented on src/tableConstructor.js
> +    const rows = (configRows || contentRows || 1);
redundant  ()

2018-11-08 16:36 UTC, neSpecc commented on src/tableConstructor.js
> +    if (event.target.classList.contains(CSS.toolBarHor) || event.target.classList.contains(CSS.toolBarVer)) {
развернуть иф и написать return

2018-11-08 16:36 UTC, neSpecc commented on src/tableConstructor.js
> +        console.log('true');
убрать лог

2018-11-08 16:36 UTC, neSpecc commented on src/tableConstructor.js
> +      const detailHasData = typeof event.detail !== 'number' && event.detail !== null;
`typeof event.detail !== 'number'` -> `isNaN()`

2018-11-08 16:36 UTC, neSpecc commented on src/tableConstructor.js
>    _keyDownListener(event) {
containerKeydown

2018-11-08 16:36 UTC, neSpecc commented on src/tableConstructor.js
>      this._side = event.detail.side;
hoveredCellSide

2018-11-08 16:36 UTC, neSpecc commented on src/tableConstructor.js
> +    this._coveredBlock = event.target.closest('TD');
hoveredCell

2018-11-08 16:36 UTC, neSpecc commented on src/tableConstructor.js
> +   * Calculates the place where you can insert a new row or column so that it is beside the element, depending on this._side
Calculates where to insert a new row/column
depending on hovered cell side

2018-11-08 16:36 UTC, neSpecc commented on src/tableConstructor.js
> +  _calculatePositionForInserting(element, withAnError = true) {
element - activeRowOrCell

2018-11-08 16:36 UTC, neSpecc commented on src/tableConstructor.js
> +      newstr.cells[0].click();
// focus first cell

2018-11-08 16:36 UTC, neSpecc commented on src/tableConstructor.js
> +    if (this._table.selectedCell !== null && !event.shiftKey) {
развернуть иф

2018-11-08 16:36 UTC, neSpecc commented on src/tableConstructor.js
> +  _calculatePositionForInserting(element, withAnError = true) {
избавить от withAnError или дать понятное название

2018-11-14 19:08 UTC, neSpecc requested changes
- прогнать через ESLint

2018-11-14 19:08 UTC, neSpecc commented on src/tableConstructor.pcss
> +s/* tcm - project's prefix*/
```suggestion
/* tcm - project's prefix*/
```

2018-11-18 08:01 UTC, neSpecc approved these changes

2018-11-18 16:54 UTC, merged